spring:
  zipkin:
    enabled: false
    baseUrl: http://localhost:9411/
  cloud:
    consul:
#      discovery:
#       preferIpAddress: true
      host: consul-consul-server
      port: 8500

management:
  endpoints:
    web:
      exposure:
        include: "*"
